export enum Status {
  SUCCESS = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  METHOD_NOT_ALLOWED = 405,
  GATEWAY_TIMEOUT = 504
}

export enum GoalType {
  PERFORMANCE = 'performance',
  DISTANT = 'distant',
  SOON = 'soon',
  RESULT = 'result',
  LEARNING = 'learning'
}

export enum RewardType {
  SMALL = 'small',
  MEDIUM = 'medium',
  BIG = 'big'
}

export enum WeekDay {
  MONDAY = 'monday',
  TUESDAY = 'tuesday',
  WEDNESDAY = 'wednesday',
  THURSDAY = 'thursday',
  FRIDAY = 'friday',
  SATURDAY = 'saturday',
  SUNDAY = 'sunday'
}

export enum MotivationType {
  PER_USER = 'per user',
  PER_GOAL = 'per goal'
}

export enum Param {
  BIG_GOAL = 'bigGoal',
  ID = 'id'
}

export enum TechniqueNumber {
  SCALABLE_LOOP = 1,
  USER_IMPULSE = 2,
  GOAL_VISUAL_PROSPECTY = 3,
  GOAL_OPTIMISTIC_LEVEL = 4,
  GOAL_WORST_CONTEXT = 5,
  USER_DEPENDENCY = 6,
  GOAL_OPTIMAL_ACCOUNTABILITY = 7,
  TASK_CALIBRATION = 8,
  GOAL_PURPOSE_PASSION = 9,
  GOAL_TOTAL_STRUCTURE_FOCUS = 10,
  GOAL_REDI = 11,
  ENJOYABLE_PRODUCTIVITY = 12,
  USER_TASK_SAMURAI = 13,
  GOAL_OPTIMIZED_ENERGY = 14,
  USER_PRODUCTIVE_PROCRASTINATION = 15,
  REWARD = 16,
  EXCHANGE_ACTIVITIES = 17,
  USER_DISTRACTION_LIMITATION = 18,
  GOAL_CONTAMINATE_TEMPTATION = 19,
  GOAL_INTERRUPTION_STIMULUS = 20,
  GOAL_PRECOMMITMENT = 21,
  GOAL_REDUCE_ALTERNATIVE = 22,
  GOAL_AUTOMATIC_HABIT = 23,
  GAME = 24,
  TASK_DISTRIBUTION_MODEL = 25,
  ADVANCE_PROGRESS_OBJECTIVES = 26,
  FALACE_MENTAL_PROJECTION = 27
}
